# discovery-service/src/main/resources/application-docker.yml
server:
    port: 8761

spring:
    application:
        name: discovery-service

eureka:
    instance:
        hostname: discovery-service
        prefer-ip-address: true
    client:
        registerWithEureka: false
        fetchRegistry: false
        service-url:
            defaultZone: http://discovery-service:${server.port}/eureka/
    server:
        myUrl: http://discovery-service:${server.port}/eureka/
# Health check
management:
    endpoints:
        web:
            exposure:
                include: health,info,gateway
    endpoint:
        health:
            show-details: always